# === 📄 File Names ===
IMAGE_PATH= {
                "image_path": "../Day 25"
            }

IMAGE_NAME = {
                "image_name": "blank_state_img.gif"
            }

#ENTRY SETTING
ENTRY_ROW=0
ENTRY_COLUMN=1
ENTRY_PX=4
ENTRY_PY=6
ENTRY_STICKY="ew"

#GUESS LABEL SETTING
GUESS_ROW=0
GUESS_COLUMN=0
GUESS_PX=4
GUESS_PY=6
GUESS_STICKY="w"

#WRONG GUESS COUNT LABEL
WRONG_COUNT_ROW=1
WRONG_COUNT_COLUMN=0
WRONG_COUNT_SPAN=2
WRONG_COUNT_PX=4
WRONG_COUNT_STICKY="w"

#BUTTON SETTINGS
OK_BTN_ROW=2
OK_BTN_COLUMN=0
OK_BTN_PX=4
OK_BTN_PY=6
OK_BTN_STICKY="ew"

CANCEL_BTN_ROW=2
CANCEL_BTN_COLUMN=1
CANCEL_BTN_PX=4
CANCEL_BTN_PY=6
CANCEL_BTN_STICKY="ew"

#WRITING TURTLE SETTING
WRITING_ALIGN="center"
WRITING_FONT=("Arial", 8, "normal")

#SCREEN TURTLE SETTING
REF_W=725
REF_H=491  # Bu görsel için tipik ölçü (Angela Yu dataset)

#TKINTER SETTING
TK_WIDTH=270
TK_HEIGHT=90
